---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poc-003
  labels:
    app: poc-003
subjects:
  - kind: ServiceAccount
    name: poc-003
roleRef:
  kind: Role
  name: poc-003
  apiGroup: rbac.authorization.k8s.io
