apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The 'namespace' field is updated automatically by the Makefile file
# Use OCP_NAMESPACE env variable for changing this
namespace: freeipa

# bases:
#   - ../base

resources:
  - common/
  - pod-main.yaml

# generators:
#   - 

# transformers:
#   -

vars:
- fieldref:
    fieldPath: data.IPA_SERVER_HOSTNAME
  name: IPA_SERVER_HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: config
- fieldref:
    fieldPath: data.IPA_SERVER_REALM
  name: IPA_SERVER_REALM
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: config
- fieldref:
    fieldPath: data.IPA_SERVER_CA_SUBJECT
  name: IPA_SERVER_CA_SUBJECT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: config

configurations:
- kustomizeconfig.yaml
