---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base/

commonLabels:
  app: poc-004-4a

resources:
  - pod-services.yaml
  - service-tcp.yaml
  - service-udp.yaml
  - service-web.yaml
