---
apiVersion: v1
kind: Pod
metadata:
  name: poc-05-b
  labels:
    app: poc-05-b
  annotations:
    openshift.io/scc: anyuid
spec:
  serviceAccountName: init-container
  automountServiceAccountToken: true
  hostAliases:
    - ip: "127.0.0.1"
      hostnames:
        - "ipa.example.test"
  containers:
    - name: main
      image: docker.io/openshift/origin-cli:v4.0
      resources:
        limits:
          cpu: "2"
          memory: "3Gi"
      securityContext:
        privileged: false
        capabilities:
          add:
            - "SYS_ADMIN"
            - "SYS_RESOURCE"
            - "MKNOD"
            - "SYS_RAWIO"
            - "SETUID"
            - "SETGID"
            - "SETPCAP"
      command: ["/usr/sbin/init"]
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: UID_BASE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: UID_BASE
        - name: GID_BASE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: GID_BASE
      volumeMounts:
        - name: scripts
          mountPath: /opt/init-container
  initContainers:
    - name: init-container-uuid
      image: docker.io/openshift/origin-cli:v4.0
      resources:
        limits:
          cpu: "1"
          memory: "48Mi"
      command: ["/opt/init-container/init-container-uuid.sh"]
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: container_uuid
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: container_uuid
      volumeMounts:
        - name: scripts
          mountPath: /opt/init-container

    - name: init-uid-gid-base
      image: docker.io/openshift/origin-cli:v4.0
      resources:
        limits:
          cpu: "1"
          memory: "48Mi"
      command: ["/opt/init-container/init-uid-gid-base.sh"]
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: UID_BASE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: UID_BASE
        - name: GID_BASE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: GID_BASE
      volumeMounts:
        - name: scripts
          mountPath: /opt/init-container

    - name: init-volume
      image: quay.io/avisied0/freeipa-openshift-container:dev-test
      resources:
        limits:
          cpu: "2"
          memory: "3Gi"
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: false
        capabilities:
          add:
            - "SYS_ADMIN"
            - "SYS_RESOURCE"
            - "MKNOD"
            - "SYS_RAWIO"
            - "SETUID"
            - "SETGID"
            - "SETPCAP"
      command: ["/usr/sbin/init"]
      args:
        - exit-on-finished
        - -U
        # - --hostname
        # - ipa.example.test
        - --realm
        - EXAMPLE.TEST
        - --no-ntp
        - --no-sshd
        - --no-ssh
        - --no-dns
        - --verbose
      env:
        # - name: SYSTEMD_OPTS
        #   value: "--show-status=true --unit=ipa-server-configure-first.service"
        - name: INIT_WRAPPER
          value: "1"
        - name: DEBUG_TRACE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: DEBUG_TRACE
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: PASSWORD
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: UID_BASE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: UID_BASE
        - name: GID_BASE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: GID_BASE
        - name: IPA_SERVER_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: IPA_SERVER_HOSTNAME
        - name: container_uuid
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: container_uuid
#         - name: IPA_SERVER_IP
#           valueFrom:
#             fieldRef:
#               fieldPath: status.podIP

        - name: container
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: container
        - name: SYSTEMD_OFFLINE
          value: "1"
        - name: SYSTEMD_NSPAWN_API_VFS_WRITABLE
          value: "network"
        # - name: IPA_SERVER_IP
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.podIP
      volumeMounts:
        - name: data
          mountPath: /data

    - name: init-uid-gid
      image: quay.io/avisied0/freeipa-openshift-container:dev-1
      resources:
        limits:
          cpu: "1"
          memory: "48Mi"
      command: ["/opt/init-container/init-ipa-server-install.sh"]
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: UID_BASE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: UID_BASE
        - name: GID_BASE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: GID_BASE
      volumeMounts:
        - name: scripts
          mountPath: /opt/init-container
        - name: data
          mountPath: /data

    - name: init-ipa-server-install
      image: quay.io/avisied0/freeipa-openshift-container:dev-1
      resources:
        limits:
          cpu: "2"
          memory: "2Gi"
      command: ["/opt/init-container/init-ipa-server-install.sh"]
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: UID_BASE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: UID_BASE
        - name: GID_BASE
          valueFrom:
            configMapKeyRef:
              name: poc-05-b
              key: GID_BASE
      volumeMounts:
        - name: scripts
          mountPath: /opt/init-container
        - name: data
          mountPath: /data

  volumes:
    - name: data
      emptyDir: {}
    - name: scripts
      configMap:
        name: poc-05-b
        items:
          - key: "init-container-uuid.sh"
            path: "init-container-uuid.sh"
            mode: 0777
          - key: "init-uid-gid-base.sh"
            path: "init-uid-gid-base.sh"
            mode: 0777
          - key: "main.sh"
            path: "main.sh"
            mode: 0777
          - key: "init-ipa-server-install.sh"
            path: "init-ipa-server-install.sh"
            mode: 0777
          - key: "passwd.example"
            path: "passwd"
            mode: 0660
          - key: "group.example"
            path: "group"
            mode: 0660
