---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: freeipa-workload
rules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - idm
    resources:
    - securitycontextconstraints
    verbs:
    - use
