---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: freeipa-workload-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: freeipa-workload
subjects:
  - kind: ServiceAccount
    name: freeipa-workload
