---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poc-004
  labels:
    app: poc-004
subjects:
  - kind: ServiceAccount
    name: poc-004
roleRef:
  kind: Role
  name: poc-004
  apiGroup: rbac.authorization.k8s.io
