---
apiVersion: v1
kind: Namespace
metadata:
  name: freeipa
  labels:
    app: freeipa
  annotations:
    openshift.io/description: "Namespace which store Freeipa resources"
    openshift.io/display-name: "Freeipa"
