apiVersion: v1
kind: ConfigMap
metadata:
  name: poc-03
  labels:
    app: poc-03
data:
  init-my-pod-id.sh: |
    #!/bin/sh
    echo "Script: $0"
    echo "NAMESPACE=${NAMESPACE}"
    echo "MY_POD_IP=${MY_POD_IP}"
  main.sh: |
    #!/bin/sh
    echo "Script: $0"
    echo "NAMESPACE=${NAMESPACE}"
    echo "MY_POD_IP=${MY_POD_IP}"
    while true; do sleep 1; done
