apiVersion: v1
kind: Pod
metadata:
  name: poc-03
  labels:
    app: poc-03
spec:
  containers:
    - name: main
      image: docker.io/openshift/origin-cli:v4.0
      resources:
        limits:
          cpu: 1
          memory: 64Mi
        requests:
          cpu: 1
          memory: 64Mi
      command: ["/opt/poc-03/main.sh"]
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumeMounts:
        - name: scripts
          mountPath: /opt/poc-03
  initContainers:
    - name: init-my-pod-id
      image: docker.io/openshift/origin-cli:v4.0
      command: ["/opt/poc-03/init-my-pod-id.sh"]
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumeMounts:
        - name: scripts
          mountPath: /opt/poc-03
  volumes:
    - name: scripts
      configMap:
        name: poc-03
        items:
          - key: "main.sh"
            path: "main.sh"
            mode: 0777
          - key: "init-my-pod-id.sh"
            path: "init-my-pod-id.sh"
            mode: 0777
