---
apiVersion: v1
kind: Pod
metadata:
  name: poc-00
  labels:
    app: poc-00
spec:
  containers:
    - name: main
      resources:
        limits:
          cpu: "2000m"
          memory: "2Gi"
      image: docker.io/openshift/origin-cli:v4.0
      command: ["/opt/poc-00/main.sh"]
      volumeMounts:
        - name: scripts
          mountPath: /opt/poc-00

  initContainers:
    - name: init-hello-world
      image: hello-world:latest

  volumes:
    - name: scripts
      configMap:
        name: poc-00
        items:
          - key: "main.sh"
            path: "main.sh"
            mode: 0777
