---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: init-container
  labels:
    app: init-container
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch", "delete", "create"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "get", "patch", "delete", "create"]
