# https://kubernetes.io/docs/concepts/services-networking/service/
---
apiVersion: v1
kind: Pod
metadata:
  name: poc-004-3-services
  labels:
    role: services
spec:
  serviceAccountName: poc-004
  containers:
    - name: http
      image: quay.io/freeipa/freeipa-operator:poc-004
      resources:
        limits:
          cpu: 400m
          memory: 64Mi
        requests:
          cpu: 200m
          memory: 64Mi
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "80"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
    - name: https
      image: quay.io/freeipa/freeipa-operator:poc-004
      resources:
        limits:
          cpu: 400m
          memory: 64Mi
        requests:
          cpu: 200m
          memory: 64Mi
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "443"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 443
          hostPort: 443
          protocol: TCP
    - name: ldap
      image: quay.io/freeipa/freeipa-operator:poc-004
      resources:
        limits:
          cpu: 400m
          memory: 64Mi
        requests:
          cpu: 200m
          memory: 64Mi
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "389"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 389
          hostPort: 389
          protocol: TCP
    - name: ldaps
      image: quay.io/freeipa/freeipa-operator:poc-004
      resources:
        limits:
          cpu: 400m
          memory: 64Mi
        requests:
          cpu: 200m
          memory: 64Mi
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "636"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 636
          hostPort: 636
          protocol: TCP
    - name: kerberos-tcp
      image: quay.io/freeipa/freeipa-operator:poc-004
      resources:
        limits:
          cpu: 400m
          memory: 64Mi
        requests:
          cpu: 200m
          memory: 64Mi
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "88"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 88
          hostPort: 88
          protocol: TCP
    - name: kerberos-admin-tcp
      image: quay.io/freeipa/freeipa-operator:poc-004
      resources:
        limits:
          cpu: 400m
          memory: 64Mi
        requests:
          cpu: 200m
          memory: 64Mi
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "464"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 464
          hostPort: 464
          protocol: TCP
    - name: kerberos-udp
      image: quay.io/freeipa/freeipa-operator:poc-004
      resources:
        limits:
          cpu: 400m
          memory: 64Mi
        requests:
          cpu: 200m
          memory: 64Mi
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "88"
        - name: "ECHO_PROTOCOL"
          value: "udp"
      ports:
        - containerPort: 88
          hostPort: 88
          protocol: UDP
    - name: kerberos-admin-udp
      image: quay.io/freeipa/freeipa-operator:poc-004
      resources:
        limits:
          cpu: 400m
          memory: 64Mi
        requests:
          cpu: 200m
          memory: 64Mi
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "464"
        - name: "ECHO_PROTOCOL"
          value: "udp"
      ports:
        - containerPort: 464
          hostPort: 464
          protocol: UDP
