# https://kubernetes.io/docs/concepts/services-networking/service/
---
apiVersion: v1
kind: Service
metadata:
  name: poc-004-3
spec:
  type: NodePort
  selector:
    app: poc-004-3
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: ldap
      protocol: TCP
      port: 389
    - name: ldaps
      protocol: TCP
      port: 636
    - name: kerberos-tcp
      protocol: TCP
      port: 88
    - name: kerberos-admin-tcp
      protocol: TCP
      port: 464
    - name: kerberos-udp
      protocol: UDP
      port: 88
    - name: kerberos-admin-udp
      protocol: UDP
      port: 464
