---
apiVersion: v1
kind: Pod
metadata:
  name: poc-04
  labels:
    app: poc-04
spec:
  serviceAccountName: init-container
  automountServiceAccountToken: true    
  containers:
    - name: main
      image: docker.io/openshift/origin-cli:v4.0
      resources:
        limits:
          cpu: 1
          memory: 64Mi
        requests:
          cpu: 1
          memory: 64Mi
      command: ["/opt/poc-04/main.sh"]
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: container_uuid
          valueFrom:
            configMapKeyRef:
              name: poc-04
              key: container_uuid
      volumeMounts:
        - name: scripts
          mountPath: /opt/poc-04
  initContainers:
    - name: init-container-uuid
      image: docker.io/openshift/origin-cli:v4.0
      command: ["/opt/poc-04/init-container-uuid.sh"]
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: container_uuid
          valueFrom:
            configMapKeyRef:
              name: poc-04
              key: container_uuid
      volumeMounts:
        - name: scripts
          mountPath: /opt/poc-04
  volumes:
    - name: scripts
      configMap:
        name: poc-04
        items:
          - key: "init-container-uuid.sh"
            path: "init-container-uuid.sh"
            mode: 0777
          - key: "main.sh"
            path: "main.sh"
            mode: 0777

