---
# https://docs.openshift.com/container-platform/4.5/authentication/managing-security-context-constraints.html
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: init-container
  labels:
    app: init-container
  annotations:
    kubernetes.io/description: init-containerprovides all features of the
      restricted SCC but allows users to run with any UID and any GID.
    release.openshift.io/create-only: "true"
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- "SETUID"
- "SETGID"
- "CHOWN"
- "SETFCAP"
- "FSETID"
- "FOWNER"
- "SETPCAP"
- "DAC_OVERRIDE"
- "NET_RAW"
- "NET_BIND_SERVICE"
- "SYS_CHROOT"
- "KILL"
- "AUDIT_WRITE"
- "SYS_ADMIN"
- "SYS_RESOURCE"

- "MKNOD"
- "SYS_RAWIO"
- "SETGID"
- "SETUID"
- "SETPCAP"
allowedUnsafeSysctls:
  - '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
priority: 10
readOnlyRootFilesystem: false
# requiredDropCapabilities:
#   - MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - init-container
# groups:
#   - system:cluster-admins
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
