# https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freeipa
spec:
  selector:
    matchLabels:
      app: freeipa
  serviceName: "freeipa"
  replicas: 1
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: freeipa
      automountServiceAccountToken: true
      containers:
      - name: main
        # image: quay.io/freeipa/freeipa-openshift-container:freeipa-server
        # image: quay.io/avisied0/freeipa-openshift-container:dev-8838140
        # image: quay.io/avisied0/freeipa-openshift-container:freeipa-server
        image: quay.io/avisied0/freeipa-openshift-container:dev-060f81d
        imagePullPolicy: Always
        # SYSTEMD_LOG_LEVEL=debug INIT_WRAPPER=1 DEBUG_TRACE=2 PASSWORD=Secret123 NAMESPACE=freeipa SYSTEMD_OFFLINE=1 podman run -it quay.io/freeipa/freeipa-openshift-container:freeipa-server no-exit ipa-server-install -U --realm APPS.MYKUBE.KARMALABS.COM --ca-subject="CN=freeipa-11111, O=APPS.MYKUBE.KARMALABS.COM" --no-ntp --no-sshd --no-ssh --verbose
        # podman run -it -e SYSTEMD_LOG_LEVEL=debug -e INIT_WRAPPER=1 -e DEBUG_TRACE=2 -e PASSWORD=Secret123 -e NAMESPACE=freeipa -e SYSTEMD_OFFLINE=1  quay.io/freeipa/freeipa-openshift-container:freeipa-server no-exit ipa-server-install -U --realm APPS.MYKUBE.KARMALABS.COM --ca-subject="CN=freeipa-11111, O=APPS.MYKUBE.KARMALABS.COM" --no-ntp --no-sshd --no-ssh --verbose
        command:
        - /usr/local/sbin/init
        args:
        - no-exit
        - ipa-server-install
        - -U
        # TODO Checkout this fields before deploy
        # TODO Define variable IPA_SERVER_REALM
        - --realm
        # - APPS.MYKUBE.KARMALABS.COM
        - $(IPA_SERVER_REALM)
        # TODO Define variable IPA_SERVER_CA_SUBJECT
        # - --ca-subject=CN=freeipa-SgD5xAV, O=APPS.MYKUBE.KARMALABS.COM
        - --ca-subject=$(IPA_SERVER_CA_SUBJECT)
        # TODO Define variable IPA_SERVER_DISABLE=ntp,sshd,ssh
        - --no-ntp
        - --no-sshd
        - --no-ssh
              
        env:
        - name: SYSTEMD_LOG_LEVEL
          value: debug
        - name: SYSTEMD_LOG_COLOR
          value: "no"
        # FIXME INIT_WRAPPER is not needed anymore
        #       Remove when the container image generated at
        #       freeipa-openshift-container is properly bound to
        #       the freeipa-operator workload.
        # - name: INIT_WRAPPER
        #   value: "1"
        # FIXME Clean-up DEBUG when experimental stage is finished
        # - name: DEBUG
        #   value: "1"
        # FIXME Clean-up KRB5_TRACE when experimental stage is finished
        # - name: KRB5_TRACE
        #   value: /dev/console
        # Special behaviour for fqdn hostname is needed in k8s by setting
        # this variable.
        - name: KUBERNETES
          value: "1"
        # FIXME Clean-up PASSWORD when the workload works as expected
        # - name: PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       key: IPA_SERVER_PASSWORD
        #       name: freeipa
        #       optional: false
        # Map ADMIN_PASSWORD from the secret
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: IPA_SERVER_ADMIN_PASSWORD
              name: freeipa
              optional: false
        # Map DS_PASSWORD from the secret
        - name: DS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: IPA_SERVER_DS_PASSWORD
              name: freeipa
              optional: false
        - name: NAMESPACE
          value: freeipa
        - name: IPA_SERVER_HOSTNAME
          value: $(IPA_SERVER_HOSTNAME)
        - name: container_uuid
          value: b01e51533bce49ce92b6bd4680edd46e
        # FIXME Set this to "0"; ftweedal figured out this variable is avoiding
        #       to execute systemctl from a terminal inside the container
        #       More info at: https://systemd.io/ENVIRONMENT/
        - name: SYSTEMD_OFFLINE
          value: "1"
        - name: SYSTEMD_NSPAWN_API_VFS_WRITABLE
          value: network

        ports:
        - containerPort: 80
          name: http-tcp
          protocol: TCP
        - containerPort: 443
          name: https-tcp
          protocol: TCP

        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1500m
            memory: 3Gi

        securityContext:
          capabilities:
            add:
            - CHOWN
            - FOWNER
            - DAC_OVERRIDE
            - SETUID
            - SETGID
            - KILL
            - NET_BIND_SERVICE
            - SETPCAP
            - SETFCAP
            - SYS_ADMIN
            - SYS_RESOURCE
            drop:
            - NET_RAW
            - SYS_CHROOT
            - FSETID
            - AUDIT_CONTROL
            - AUDIT_READ
            - BLOCK_SUSPEND
            - DAC_READ_SEARCH
            - IPC_LOCK
            - IPC_OWNER
            - LEASE
            - LINUX_IMMUTABLE
            - MAC_ADMIN
            - MAC_OVERRIDE
            - NET_ADMIN
            - NET_BROADCAST
            - SYS_BOOT
            - SYS_MODULE
            - SYS_NICE
            - SYS_PACCT
            - SYS_PTRACE
            - SYS_RAWIO
            - SYS_TIME
            - SYS_TTY_CONFIG
            - SYSLOG
            - WAKE_ALARM
            - MKNOD
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true

        volumeMounts:
        - name: freeipa
          mountPath: /data
        - mountPath: /tmp
          name: systemd-tmp
        - mountPath: /var/run
          name: systemd-var-run
        - mountPath: /var/run/dirsrv
          name: systemd-var-dirsrv

      volumes:
      - emptyDir:
          medium: Memory
        name: systemd-var-run
      - emptyDir:
          medium: Memory
        name: systemd-var-dirsrv
      - emptyDir:
          medium: Memory
        name: systemd-run-rpcbind
      - emptyDir:
          medium: Memory
        name: systemd-tmp

  volumeClaimTemplates:
  - metadata:
      name: freeipa
    spec:
      volumeMode: Filesystem
      volumeName: freeipa
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
